### ISSUE TITLE
fix?

### ISSUE THREAD

**Issue by VC1W** [Cyrex0/KeyAuth-MemJect#3]
could you fix this code ?

**Comment by Cyrex0** [comment]
> could you fix this code ?

whats the problem your having with it, its just a basic example for x64 injection

**Comment by Buskso** [comment]
Ye but like to make it x86. I would highly appreciate it

**Comment by Cyrex0** [comment]
> Ye but like to make it x86. I would highly appreciate it

nah man, plenty examples for x86 injection our there, this was just a quick example for people
